/**
  * Problem 29. Distinct powers
  *
  * Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:
  * If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:
  * 4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
  * How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
  *
  * https://projecteuler.net/problem=29
  **/

var map = collection.mutable.Map[BigInt, Int]()

val (aMax, bMax) = (100, 100)

for (a <- 2 to aMax) {
  for (b <- 2 to bMax) {
    val n = BigInt(a).pow(b)

    if (!(map isDefinedAt n)) {
      map += (n->1)
    }
  }
}

println(map.size)
/*
9183

real    0m1.360s
user    0m1.313s
sys     0m0.142s

 */