/**
  * Problem 44. Pentagon numbers
  *
  * Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
  * 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
  * It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
  * Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
  *
  * https://projecteuler.net/problem=44
  **/


def pentagon(n: Int): Long = {
   n * (3 * n - 1) / 2
}

var pNumbers = new Array[Long](10000)

for (n <- 1 until pNumbers.length) {
  pNumbers(n) = pentagon(n)
}

// n(3n - 1)/2 = x
// 3n^2 - n = 2x
// 3n^2 - n - 2x = 0
// x can be found using quadratic equation
// a = 3, b = -1, c = 2x
def isPentagonal(x: Long): Boolean = {
  val n = math.sqrt(1 + 24 * x) + 1
  n % 6 == 0
}


for (j <- 1 to pNumbers.length - 1) {
  for (k <- j + 1 to pNumbers.length - 1) {
    if (isPentagonal(pNumbers(k) + pNumbers(j)) && isPentagonal(pNumbers(k) - pNumbers(j))) {
      println(pNumbers(k) + ", " + pNumbers(j) + "  D= " + (pNumbers(k) - pNumbers(j)))
    }
  }
}


/*
7042750, 1560090  D= 5482660

real    0m3.419s
user    0m3.364s
sys     0m0.120s

NOTE: Another pair found with array size 100k
503033278, 85908152  D= 417125126

 */